#!/bin/sh

if pgrep parec
then 
    # Stop recording audio
    pkill parec
else
    # Output device (the default one)
    # For more use "pacmd list-sinks | grep -e 'name:' -e 'index' -e 'Speakers'" command
    targetSink="@DEFAULT_MONITOR@"


    # 5-character random string
    rand=$(cat /dev/urandom | tr -dc 'A-Z0-9' | fold -w 7 | head -n 1)

    # Construct filename
    filename="$(xdg-user-dir DOWNLOAD)/out_${rand}.mp3"

    # Start notification showing recording in progress
    notificationId=$(notify-send -p -u critical -a record_audio_output -i audio-on 'Recording in progress' "Desktop audio is being recorded to $filename.")

    # Record audio to the file
    parec -d $targetSink --volume=65536 | lame -r -V7 - $filename

    # Replace notification
    notify-send -u normal -r $notificationId -a record_audio_output -i audio-off 'Recording finished' "Desktop audio recorded to $filename. Path copied to clipboard"

    # Copy the file to the clipboard
    echo "file://${filename}"|xclip -i -sel c -t text/uri-list
fi
